# Generated by Django 5.0.7 on 2024-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopetoproposal', '0003_image_name_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('tel', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
