# Generated by Django 5.0.7 on 2024-07-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopetoproposal', '0004_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(blank=True, default='(011) 425 6352', max_length=200),
        ),
    ]
